sudo: required
services:
  - docker


before_install:
  - docker build -t texplode/mkb-server  .

script:
  - docker run texplode/mkb-server
  # - docker-compose down

after_success:
  - docker build -t texplode/mkb-nginx  ./nginx
  - docker build -t texplode/mkb-server  .


# Login to Docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# Take images and push them to dockerhub

  - docker push texplode/mkb-nginx
  - docker push texplode/mkb-server




# Mkobo

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "mkb"
  env: "mock" 
  bucket_name: "elasticbeanstalk-us-east-2-097267457133"
  bucket_path: "mkb-bucket"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"