export const findUser = 'SELECT * FROM users WHERE email=$1';
export const createUser = 'INSERT INTO users (email, password, firstname, lastname) VALUES ($1, $2, $3, $4) returning *';
export const addTeam = 'INSERT INTO teams (name) VALUES ($1) returning *';
export const findTeamById = 'SELECT * FROM teams WHERE id=$1';
export const findTeamByName = 'SELECT * FROM teams WHERE name=$1';
export const allTeamsQuery = 'SELECT * FROM teams';
export const editTeamQuery = 'UPDATE teams SET name = $1 WHERE id = $2 returning *';
export const deleteTeamQuery = 'DELETE FROM teams WHERE id=$1 returning *';
export const addFixtureQuery = 'INSERT INTO fixtures (hometeam,awayteam,hometeamscore,awayteamscore,matchdate,venue,link) VALUES ($1,$2,$3,$4,$5,$6,$7) returning *';
export const findFixtureById = 'SELECT * FROM fixtures WHERE id=$1';
export const allFixturesQuery = 'SELECT * FROM fixtures';
export const editFixtureQuery = 'UPDATE fixtures SET hometeamscore=$1, awayteamscore=$2 WHERE id=$3 returning *';
export const deleteFixtureQuery = 'DELETE FROM fixtures WHERE id=$1 returning *';
export const completedStatusSearch= 'SELECT * FROM fixtures WHERE completed';
export const pendingStatusSearch= 'SELECT * FROM fixtures WHERE NOT completed';
export const hometeamQuery= 'SELECT * FROM fixtures WHERE hometeam=$1';
export const awayteamQuery= 'SELECT * FROM fixtures WHERE awayteam=$1';
export const beforeDateQuery = 'SELECT * FROM fixtures WHERE matchdate < $1';
export const afterDateQuery = 'SELECT * FROM fixtures WHERE matchdate > $1';
